configs:
  use: 'dev'
  dev:
    box: 'bento/centos-7.1'
    memory_size: '4096'
    public_ip: '10.20.1.33'
    shell_scripts_path: 'scripts'
    db_user: 'lportal'
    db_password: 'lportal'
    db_name: 'lportal'
    lr_user: 'lportal'
    lr_file: 'liferay-portal-tomcat-7.0-ce-a3-20151119130239619.zip'
    lr_download_path: ''
